### PR TITLE
[7.0] split invoicing into parts

### PR DESCRIPTION
**Pull request by veloutin**
We are doing invoicing through xmlrpc calls of invoice batches. With this PR, the invoicing process can be tackled in parallel batches by splitting the invoice numbering bottleneck into its own operation.

### CODE REVIEW

**Comment by joaoalf** [comment]
@veloutin Will this change impact the invoice workflow?

**Comment by veloutin** [comment]
@joaoalf I have tried to make no impact. The top-level "create_invoice" and "proforma_voucher" functions do the same thing. They both:
1) Create the invoice
2) Open the invoice
3) Mail the invoice

The difference I can see right now is that in proforma_voucher() now respects the company "send_email_contract_invoice" field instead of always sending.

**Comment by gurneyalex** [comment]
:+1:

**Comment by joaoalf** [comment]
:+1:

**Review by max3903 — APPROVED** [review]

**Pull request merged**
