### PR TITLE
[META] travis config: transifex, apt, test matrix and improved coveralls

### PR DESCRIPTION
**Pull request by veloutin**

### CODE REVIEW

**Comment by max3903** [comment]
It may be a good time to add transifex configuration as well:
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml
https://github.com/OCA/maintainer-quality-tools/issues/194

**Comment by veloutin** [comment]
@max3903 Does someone from OCA need to create the project on transifex, and supply the encrypted password, or can I cut and paste from the sample?

**Comment by max3903** [comment]
@veloutin No need to create anything. You cut and paste from the sample and you change the secret from the 2nd link.

**Comment by bwrsandman** [comment]
This is a good time to use the updated test matrix from the sample files as well as the conditional coveralls submission

**Comment by veloutin** [comment]
@max3903 @bwrsandman OK, will do.

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
